[server]
enableStaticServing = true
port = 8501
address = "0.0.0.0"

[browser]
gatherUsageStats = false

[runner]
magicEnabled = false

[theme]
base = "light"
backgroundColor = "#f1f4f9"
secondaryBackgroundColor = "#ffffff"
textColor = "#1a2332"
primaryColor = "#059669"
font = "sans serif"
